profile:
  name: pro
datasource:
  url: jdbc:mysql://localhost:3306/springcloud
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: Angel521